# Generated by Django 6.0 on 2026-03-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fort_name', models.CharField(max_length=100)),
                ('driver_name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('pickup_date', models.DateField()),
                ('seats', models.IntegerField()),
                ('price', models.IntegerField()),
                ('offer_price', models.IntegerField()),
                ('book_seats', models.IntegerField()),
            ],
        ),
    ]