# Generated by Django 6.0 on 2026-03-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='pickup_place',
            field=models.CharField(default='Pune', max_length=150),
            preserve_default=False,
        ),
    ]
