# Generated by Django 6.0 on 2026-03-09 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_package_pickup_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='book_seats',
        ),
        migrations.AlterField(
            model_name='package',
            name='contact',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10 digit mobile number', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='package',
            name='pickup_place',
            field=models.CharField(default='Pune', max_length=150),
        ),
    ]
