# Generated by Django 6.0 on 2026-03-30 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_package_book_seats_alter_package_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=100)),
                ('your_address', models.TextField()),
                ('your_contact', models.CharField(max_length=15)),
                ('driver_name', models.CharField(max_length=100)),
                ('trip_date', models.DateField()),
                ('contact', models.CharField(max_length=15)),
                ('package_name', models.CharField(max_length=100)),
                ('payment_method', models.CharField(default='Cash', max_length=20)),
            ],
        ),
    ]
