# Generated by Django 6.0 on 2026-03-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='seats_booked',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
