# Generated by Django 6.0 on 2026-03-31 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_booking_seats_booked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='id',
        ),
        migrations.AddField(
            model_name='booking',
            name='seats_booked',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='your_email',
            field=models.EmailField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
