# Generated by Django 6.0 on 2026-03-31 14:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_booking_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='password',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userregister',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10 digit mobile number', regex='^\\d{10}$')]),
        ),
    ]
