# Generated by Django 6.0 on 2026-04-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_userregister_password_alter_userregister_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='created_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
