# Generated by Django 6.0 on 2026-04-01 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_package_created_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='package',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.package'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='package',
            name='contact',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='package',
            name='pickup_place',
            field=models.CharField(max_length=150),
        ),
    ]
